---
- name: Install Docker on Amazon Linux
  hosts: seq
  become: true

  tasks:
    - name: Install docker
      ansible.builtin.yum:
        name:
          - docker
        state: present

    - name: Start and enable Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true
